USE [master]
GO

ALTER DATABASE AdventureWorksStaging2012
SET ALLOW_SNAPSHOT_ISOLATION ON  

ALTER DATABASE AdventureWorksStaging2012
SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT

ALTER DATABASE AdventureWorksDatamart2012
SET ALLOW_SNAPSHOT_ISOLATION ON  

ALTER DATABASE AdventureWorksDatamart2012
SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT